# Generated by Django 3.2.3 on 2021-05-29 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Тема')),
                ('created', models.DateTimeField(blank=True, help_text='Дата создания заявки', verbose_name='Создано')),
                ('modified', models.DateTimeField(blank=True, help_text='Дата последнего создания заявки.', verbose_name='Изменено')),
                ('submitter_email', models.EmailField(blank=True, help_text='Электронная почта отправителя', max_length=254, null=True, verbose_name='Электронная почта отправителя')),
                ('status', models.CharField(choices=[('Открыта', 'Открыта'), ('Переоткрыта', 'Переоткрыта'), ('Решено', 'Решено'), ('Закрыта', 'Закрыта'), ('Дубль', 'Дубль')], default='Открыта', max_length=32, verbose_name='Статус')),
                ('description', models.TextField(blank=True, help_text='Описание заявки', null=True, verbose_name='Описание')),
                ('resolution', models.TextField(blank=True, help_text='Решение сотрудника', null=True, verbose_name='Решение')),
                ('priority', models.CharField(blank='Обыная', choices=[('Критическая', '1. Критическая'), ('Высокая', '2. Высокая'), ('Обыная', '3. Обыная'), ('Низкая', '4. Низкая'), ('Очень низкая', '5. Очень низкая')], default='Обыная', max_length=32, verbose_name='Приоритет')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to=settings.AUTH_USER_MODEL, verbose_name='Назначен')),
            ],
        ),
    ]
